---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: blockvisor-ui
spec:
  domains:
    - app.blockjoy.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blockvisor-ui
  annotations:
    kubernetes.io/ingress.global-static-ip-name: blockvisor-ui
    networking.gke.io/managed-certificates: blockvisor-ui
    kubernetes.io/ingress.class: gce
    networking.gke.io/v1beta1.FrontendConfig: blockvisor-ui
spec:
  defaultBackend:
    service:
      name: blockvisor-ui
      port:
        number: 3000
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: blockvisor-ui
spec:
  redirectToHttps:
    enabled: true
---