name: tests
on:
  push:
    branches:
      - feature/cypress-testing
jobs:
  cypress-run:
    env:
      ENV_SECRETS: ${{ secrets.TESTING_SECRETS }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download environment secrets
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/.env.production
          encodedString: ${{ env.ENV_SECRETS }}
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Vitest run
        run: yarn test
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
